<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-25T11:35:31 ICT" name="Oce Test Suite" finished-at="2025-04-25T11:35:51 ICT" duration-ms="19757">
    <groups>
    </groups>
    <test started-at="2025-04-25T11:35:31 ICT" name="Testcases.Railway" finished-at="2025-04-25T11:35:51 ICT" duration-ms="19757">
      <class name="Testcases.Railway.BookTicketsTests">
        <test-method is-config="true" signature="setUp()[pri:0, instance:Testcases.Railway.BookTicketsTests@10d307f1]" started-at="2025-04-25T11:35:31 ICT" name="setUp" finished-at="2025-04-25T11:35:39 ICT" duration-ms="8009" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="TC04()[pri:0, instance:Testcases.Railway.BookTicketsTests@10d307f1]" started-at="2025-04-25T11:35:39 ICT" name="TC04" description="TC04 - Người dùng có thể đăng nhập vào Railway với tài khoản và mật khẩu hợp lệ" finished-at="2025-04-25T11:35:43 ICT" duration-ms="3424" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC04 -->
        <test-method signature="TC14()[pri:0, instance:Testcases.Railway.BookTicketsTests@10d307f1]" started-at="2025-04-25T11:35:43 ICT" name="TC14" finished-at="2025-04-25T11:35:49 ICT" duration-ms="6674" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Invalid field name: Depart Date]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Invalid field name: Depart Date
at Railway.pages.BookTicketsPage.getColumnIndex(BookTicketsPage.java:79)
at Railway.pages.BookTicketsPage.isTicketInfoCorrect(BookTicketsPage.java:83)
at Testcases.Railway.BookTicketsTests.TC14(BookTicketsTests.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC14 -->
        <test-method signature="TC16()[pri:0, instance:Testcases.Railway.BookTicketsTests@10d307f1]" started-at="2025-04-25T11:35:49 ICT" name="TC16" finished-at="2025-04-25T11:35:51 ICT" duration-ms="1307" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Menu item 'Login' not found!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Menu item 'Login' not found!
at Railway.pages.GenetralPage.clickMenuItem(GenetralPage.java:75)
at Testcases.Railway.BookTicketsTests.TC16(BookTicketsTests.java:71)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC16 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Testcases.Railway.BookTicketsTests@10d307f1]" started-at="2025-04-25T11:35:51 ICT" name="tearDown" finished-at="2025-04-25T11:35:51 ICT" duration-ms="277" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Testcases.Railway.BookTicketsTests -->
    </test> <!-- Testcases.Railway -->
  </suite> <!-- Oce Test Suite -->
</testng-results>
